name: donrua_app
description: "Aplicaci贸n para la automatizaci贸n de los procesos de intenciones y
  Donaciones (versi贸n m贸vil)."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.8
  google_fonts: ^6.2.1
  icons_plus: ^5.0.0
  widget_zoom: ^0.0.4

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/google_fonts/
    - assets/img/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/google_fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/google_fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/google_fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/google_fonts/Poppins-SemiBold.ttf
          weight: 600
